# Generated by Django 4.2.5 on 2023-10-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_factor_job_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiFactorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_id', models.CharField(max_length=10)),
                ('Question', models.TextField()),
                ('primaryfacts', models.CharField(max_length=10)),
                ('otherfacts', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='otherfact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
